<#
.SYNOPSIS
    Setup 'ncdeploy' command to work from any directory

.DESCRIPTION
    Adds a PowerShell function to your profile that allows you to run 'ncdeploy'
    from any directory. The function automatically locates and executes the 
    ncdeploy.ps1 script from the workspace Scripts folder.

.EXAMPLE
    .\setup-ncdeploy-alias.ps1
    
    After running this once, you can use 'ncdeploy' from any directory:
    PS C:\Users\You> ncdeploy
    PS D:\SomeOtherFolder> ncdeploy -SkipMerge
#>

$ErrorActionPreference = "Stop"

# Get the workspace root (parent of Scripts folder)
$ScriptRoot = $PSScriptRoot
$WorkspaceRoot = Split-Path $ScriptRoot -Parent
$NcdeployPath = Join-Path $ScriptRoot "ncdeploy.ps1"

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "  Setup ncdeploy Global Command" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

# Verify ncdeploy.ps1 exists
if (-not (Test-Path $NcdeployPath)) {
    Write-Host "❌ Error: ncdeploy.ps1 not found at $NcdeployPath" -ForegroundColor Red
    exit 1
}

Write-Host "✓ Found ncdeploy.ps1 at: $NcdeployPath" -ForegroundColor Green

# Check if profile exists
$profileExists = Test-Path $PROFILE
if (-not $profileExists) {
    Write-Host "→ Creating PowerShell profile at: $PROFILE" -ForegroundColor Yellow
    New-Item -ItemType File -Path $PROFILE -Force | Out-Null
    Write-Host "✓ Profile created" -ForegroundColor Green
} else {
    Write-Host "✓ Found existing profile at: $PROFILE" -ForegroundColor Green
}

# Read current profile content
$profileContent = Get-Content $PROFILE -Raw -ErrorAction SilentlyContinue

# Check if ncdeploy function already exists
if ($profileContent -match "function ncdeploy") {
    Write-Host "`n⚠ 'ncdeploy' function already exists in profile" -ForegroundColor Yellow
    $response = Read-Host "Update it? (y/n)"
    if ($response -ne 'y') {
        Write-Host "Cancelled." -ForegroundColor Gray
        exit 0
    }
    
    # Remove old function
    $profileContent = $profileContent -replace '(?s)# NCDEPLOY FUNCTION START.*?# NCDEPLOY FUNCTION END\r?\n', ''
}

# Create the function definition
$functionDef = @"

# NCDEPLOY FUNCTION START
# Auto-generated by setup-ncdeploy-alias.ps1
function ncdeploy {
    [CmdletBinding()]
    param(
        [switch]`$SkipMerge,
        [switch]`$SkipBuild,
        [switch]`$SkipIIS,
        [switch]`$AutoMerge,
        [string]`$AppPool = "NoorCanvas"
    )
    
    & "$NcdeployPath" @PSBoundParameters
}
# NCDEPLOY FUNCTION END

"@

# Append function to profile
Add-Content -Path $PROFILE -Value $functionDef

Write-Host "`n✓ 'ncdeploy' function added to profile" -ForegroundColor Green
Write-Host "`nTo activate immediately, run:" -ForegroundColor Cyan
Write-Host "  . `$PROFILE" -ForegroundColor White
Write-Host "`nOr simply restart your PowerShell session." -ForegroundColor Gray
Write-Host "`nYou can now run 'ncdeploy' from any directory!" -ForegroundColor Green
Write-Host "`nExamples:" -ForegroundColor Cyan
Write-Host "  ncdeploy" -ForegroundColor White
Write-Host "  ncdeploy -SkipMerge" -ForegroundColor White
Write-Host "  ncdeploy -SkipIIS" -ForegroundColor White
Write-Host ""
