<#
.SYNOPSIS
    Setup ncdeploy to run from any directory - Multiple methods available

.DESCRIPTION
    This script sets up the 'ncdeploy' command to work from any directory.
    Choose from three methods:
    
    1. PowerShell Profile (Recommended) - Works in PowerShell only
    2. Add Scripts folder to PATH - Works in PowerShell and CMD
    3. Copy batch file to System32 - Works everywhere (requires admin)

.EXAMPLE
    .\setup-ncdeploy-global.ps1
#>

$ErrorActionPreference = "Stop"
$ScriptRoot = $PSScriptRoot
$WorkspaceRoot = Split-Path $ScriptRoot -Parent
$NcdeployPs1 = Join-Path $ScriptRoot "ncdeploy.ps1"
$NcdeployBat = Join-Path $ScriptRoot "ncdeploy.bat"

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "  Setup ncdeploy Global Command" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

Write-Host "Choose setup method:`n" -ForegroundColor Yellow

Write-Host "1. PowerShell Profile Function (Recommended)" -ForegroundColor White
Write-Host "   - Works in: PowerShell only" -ForegroundColor Gray
Write-Host "   - Installation: Quick, no admin needed" -ForegroundColor Gray
Write-Host "   - Command: ncdeploy" -ForegroundColor Green
Write-Host ""

Write-Host "2. Add Scripts Folder to PATH" -ForegroundColor White
Write-Host "   - Works in: PowerShell and CMD" -ForegroundColor Gray
Write-Host "   - Installation: Permanent, requires admin" -ForegroundColor Gray
Write-Host "   - Commands: ncdeploy.ps1 or ncdeploy.bat" -ForegroundColor Green
Write-Host ""

Write-Host "3. Copy Batch File to System32" -ForegroundColor White
Write-Host "   - Works in: PowerShell and CMD" -ForegroundColor Gray
Write-Host "   - Installation: Simple, requires admin" -ForegroundColor Gray
Write-Host "   - Command: ncdeploy" -ForegroundColor Green
Write-Host ""

Write-Host "4. Show Manual Instructions" -ForegroundColor White
Write-Host "   - DIY approach with full paths" -ForegroundColor Gray
Write-Host ""

$choice = Read-Host "Enter choice (1-4)"

switch ($choice) {
    "1" {
        # PowerShell Profile Method
        Write-Host "`n→ Setting up PowerShell Profile Function..." -ForegroundColor Cyan
        
        $profileExists = Test-Path $PROFILE
        if (-not $profileExists) {
            Write-Host "  Creating PowerShell profile..." -ForegroundColor Gray
            New-Item -ItemType File -Path $PROFILE -Force | Out-Null
        }
        
        $profileContent = Get-Content $PROFILE -Raw -ErrorAction SilentlyContinue
        
        if ($profileContent -match "function ncdeploy") {
            Write-Host "  ⚠ Function already exists. Updating..." -ForegroundColor Yellow
            $profileContent = $profileContent -replace '(?s)# NCDEPLOY FUNCTION START.*?# NCDEPLOY FUNCTION END\r?\n', ''
        }
        
        $functionDef = @"

# NCDEPLOY FUNCTION START
# Auto-generated by setup-ncdeploy-global.ps1
function ncdeploy {
    [CmdletBinding()]
    param(
        [switch]`$SkipMerge,
        [switch]`$SkipBuild,
        [switch]`$SkipIIS,
        [switch]`$AutoMerge,
        [string]`$AppPool = "NoorCanvas"
    )
    & "$NcdeployPs1" @PSBoundParameters
}
# NCDEPLOY FUNCTION END

"@
        
        Add-Content -Path $PROFILE -Value $functionDef
        
        Write-Host "`n✅ Setup complete!" -ForegroundColor Green
        Write-Host "`nTo activate immediately:" -ForegroundColor Cyan
        Write-Host "  . `$PROFILE" -ForegroundColor White
        Write-Host "`nOr restart PowerShell, then use:" -ForegroundColor Cyan
        Write-Host "  ncdeploy" -ForegroundColor Green
    }
    
    "2" {
        # Add to PATH Method
        Write-Host "`n→ Adding Scripts folder to PATH..." -ForegroundColor Cyan
        
        # Check if running as admin
        $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
        
        if (-not $isAdmin) {
            Write-Host "`n❌ Error: This method requires administrator privileges." -ForegroundColor Red
            Write-Host "Please run PowerShell as Administrator and try again." -ForegroundColor Yellow
            exit 1
        }
        
        $currentPath = [Environment]::GetEnvironmentVariable("PATH", "Machine")
        
        if ($currentPath -like "*$ScriptRoot*") {
            Write-Host "  Scripts folder already in PATH." -ForegroundColor Green
        } else {
            $newPath = "$currentPath;$ScriptRoot"
            [Environment]::SetEnvironmentVariable("PATH", $newPath, "Machine")
            Write-Host "  ✓ Added to system PATH" -ForegroundColor Green
        }
        
        Write-Host "`n✅ Setup complete!" -ForegroundColor Green
        Write-Host "`nRestart your terminal, then use:" -ForegroundColor Cyan
        Write-Host "  ncdeploy.bat (CMD or PowerShell)" -ForegroundColor Green
        Write-Host "  ncdeploy.ps1 (PowerShell only)" -ForegroundColor Green
    }
    
    "3" {
        # Copy to System32 Method
        Write-Host "`n→ Copying batch file to System32..." -ForegroundColor Cyan
        
        # Check if running as admin
        $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
        
        if (-not $isAdmin) {
            Write-Host "`n❌ Error: This method requires administrator privileges." -ForegroundColor Red
            Write-Host "Please run PowerShell as Administrator and try again." -ForegroundColor Yellow
            exit 1
        }
        
        $system32 = "$env:SystemRoot\System32"
        $targetBat = Join-Path $system32 "ncdeploy.bat"
        
        Copy-Item -Path $NcdeployBat -Destination $targetBat -Force
        Write-Host "  ✓ Copied to $targetBat" -ForegroundColor Green
        
        Write-Host "`n✅ Setup complete!" -ForegroundColor Green
        Write-Host "`nYou can now use from anywhere:" -ForegroundColor Cyan
        Write-Host "  ncdeploy" -ForegroundColor Green
    }
    
    "4" {
        # Manual Instructions
        Write-Host "`n========================================" -ForegroundColor Cyan
        Write-Host "  Manual Usage Instructions" -ForegroundColor Cyan
        Write-Host "========================================`n" -ForegroundColor Cyan
        
        Write-Host "The script already works from any directory using full paths:`n" -ForegroundColor White
        
        Write-Host "PowerShell:" -ForegroundColor Yellow
        Write-Host "  & '$NcdeployPs1'" -ForegroundColor Green
        Write-Host "  & '$NcdeployPs1' -SkipMerge" -ForegroundColor Green
        Write-Host ""
        
        Write-Host "CMD:" -ForegroundColor Yellow
        Write-Host '  powershell -ExecutionPolicy Bypass -File "' + $NcdeployPs1 + '"' -ForegroundColor Green
        Write-Host ""
        
        Write-Host "Or create a shortcut/alias in your shell profile." -ForegroundColor Gray
    }
    
    default {
        Write-Host "`n❌ Invalid choice. Exiting." -ForegroundColor Red
        exit 1
    }
}

Write-Host ""
