# NOOR Canvas - Automated Build and Test Workflow
name: Build and Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  DOTNET_VERSION: '8.0'
  BUILD_CONFIGURATION: 'Release'

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./SPA/NoorCanvas
      
    - name: Build application
      run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}
      working-directory: ./SPA/NoorCanvas
      
    - name: Run tests
      run: dotnet test --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --verbosity normal --logger "trx;LogFileName=TestResults.trx"
      working-directory: ./Tests/NoorCanvas.Core.Tests
      
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: '**/TestResults.trx'
        reporter: dotnet-trx
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: '**/TestResults.trx'
